/* Only public Supabase values belong here. Never expose service_role. */
const SUPABASE_URL = "https://ytvrguqcgbynoxhimtei.supabase.co", SUPABASE_ANON_KEY = "sb_publishable_S_7pQstImvcCAPeF68m5Sw_t7U-vvnz", MAX_FILE_SIZE = 50 * 1024 * 1024;
const db = SUPABASE_URL && SUPABASE_ANON_KEY && window.supabase ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;
const $ = s => document.querySelector(s); let posts=[], mediaByPost=new Map(), commentsByPost=new Map(), likesByPost=new Map(), selectedFiles=[], session, channel, visible=10, gallery=[], galleryIndex=0, introDone=false;
const formatTime = d => new Intl.DateTimeFormat(undefined,{day:"numeric",month:"short",hour:"numeric",minute:"2-digit"}).format(new Date(d));
const urlFor = m => m.previewUrl || (db ? db.storage.from("post-media").getPublicUrl(m.storage_path).data.publicUrl : m.storage_path);
function memoryText(){const message=$("#message").value.trim(),link=$("#memoryUrl").value.trim();return link?`${message}\n\n${link}`:message}

function addLinks(target,text){const re=/(?:https?:\/\/|www\.)[^\s<>"']+/gi;let last=0,m;while((m=re.exec(String(text||"")))){target.append(document.createTextNode(text.slice(last,m.index)));const raw=m[0],href=raw.startsWith("www.")?`https://${raw}`:raw;try{const u=new URL(href);if(/^https?:$/.test(u.protocol)){const a=document.createElement("a");a.href=u.href;a.target="_blank";a.rel="noopener noreferrer";a.textContent=raw;target.append(a)}else target.append(document.createTextNode(raw))}catch{target.append(document.createTextNode(raw))}last=m.index+raw.length}target.append(document.createTextNode(String(text||"").slice(last)))}
function audio(){return $("#bgMusic")} function setMusic(on,play=true){sessionStorage.setItem("mw-music",on?"on":"off");$("#soundToggle").setAttribute("aria-pressed",String(on));$("#soundToggle span").textContent=on?"MUSIC ON":"MUSIC OFF";audio().volume=.25;if(on&&play)audio().play().catch(()=>{});if(!on)audio().pause()}
async function getSession(name){const saved=localStorage.getItem("mw-session-id");if(saved)return session={id:saved,display_name:localStorage.getItem("mw-display-name")||name||"Friend"};if(!db){session={id:crypto.randomUUID(),display_name:name||"Friend"};localStorage.setItem("mw-session-id",session.id);localStorage.setItem("mw-display-name",session.display_name);return session}const r=await db.from("visitor_sessions").insert({display_name:name||"Friend"}).select().single();if(r.error)throw r.error;session=r.data;localStorage.setItem("mw-session-id",session.id);localStorage.setItem("mw-display-name",session.display_name);return session}
function index(items,map,key){map.clear();items.forEach(x=>map.set(x[key],[...(map.get(x[key])||[]),x]))}function render(){renderCollage();renderFeed();$("#memoryCount").textContent=posts.length}
function renderCollage(){const box=$("#collage");box.replaceChildren();const imgs=[...mediaByPost.values()].flat().filter(x=>x.media_type==="image");if(!imgs.length){const e=document.createElement("div");e.className="collage-empty";e.textContent="THE MOSAIC IS WAITING FOR ITS FIRST PHOTO ✦";box.append(e);return}imgs.slice(0,6).forEach((m,i)=>{const b=document.createElement("button"),im=document.createElement("img"),tag=document.createElement("span");b.className="collage-item";b.style.animationDelay=`${i*80}ms`;im.src=urlFor(m);im.loading="lazy";im.alt="Memory photo";tag.className="collage-tag";tag.textContent="View memory";b.append(im,tag);b.onclick=()=>openGallery(imgs,imgs.indexOf(m));box.append(b)})}
function renderFeed(){const box=$("#feedList");box.replaceChildren(...posts.slice(0,visible).map(postCard));$("#loadMore").hidden=visible>=posts.length}
function postCard(post){const el=$("#postTemplate").content.firstElementChild.cloneNode(true),name=post.visitor_sessions?.display_name||"Friend";el.querySelector(".avatar").textContent=name[0]?.toUpperCase()||"F";el.querySelector(".post-name").textContent=name;el.querySelector("time").textContent=formatTime(post.created_at);addLinks(el.querySelector(".post-content"),post.content);const media=mediaByPost.get(post.id)||[],mb=el.querySelector(".post-media");media.forEach(m=>{let x;if(m.media_type==="video"){x=document.createElement("video");x.controls=true;x.preload="metadata"}else if(m.media_type==="audio"){x=document.createElement("audio");x.controls=true;x.preload="metadata"}else{x=document.createElement("img");x.loading="lazy";x.alt=`Memory from ${name}`;x.onclick=()=>{const g=media.filter(q=>q.media_type!=="audio");openGallery(g,g.indexOf(m))}}x.src=urlFor(m);mb.append(x)});const like=el.querySelector(".like");like.querySelector("span").textContent=likesByPost.get(post.id)||0;like.onclick=()=>likePost(post.id,like);const cb=el.querySelector(".comments");(commentsByPost.get(post.id)||[]).forEach(c=>cb.append(commentEl(c)));el.querySelector(".comment-form").onsubmit=e=>{e.preventDefault();const input=e.currentTarget.querySelector("input");if(input.value.trim())comment(post.id,input.value.trim(),input)};return el}
function commentEl(c){const d=document.createElement("div"),b=document.createElement("b"),t=document.createElement("time");d.className="comment";b.textContent=c.visitor_sessions?.display_name||"Friend";t.textContent=formatTime(c.created_at);d.append(b,document.createTextNode("  "));addLinks(d,c.content);d.append(t);return d}
async function likePost(id,button){if(button.classList.contains("liked"))return;const old=likesByPost.get(id)||0;button.classList.add("liked");likesByPost.set(id,old+1);button.querySelector("span").textContent=old+1;try{await getSession();if(db){const r=await db.from("likes").insert({post_id:id,session_id:session.id});if(r.error)throw r.error}}catch(e){button.classList.remove("liked");likesByPost.set(id,old);button.querySelector("span").textContent=old;alert(`Could not add like: ${e.message}`)}}
async function comment(id,content,input){try{await getSession();let c={id:crypto.randomUUID(),content,created_at:new Date().toISOString(),visitor_sessions:{display_name:session.display_name}};if(db){const r=await db.from("comments").insert({post_id:id,session_id:session.id,content}).select("*, visitor_sessions(display_name)").single();if(r.error)throw r.error;c=r.data}commentsByPost.set(id,[...(commentsByPost.get(id)||[]),c]);input.value="";renderFeed()}catch(e){alert(`Could not send reply: ${e.message}`)}}
function openGallery(items,i){gallery=items;galleryIndex=i;showGallery();$("#lightbox").showModal()}function showGallery(){const m=gallery[galleryIndex],box=$("#lightboxContent");box.replaceChildren();const x=document.createElement(m.media_type==="video"?"video":"img");x.src=urlFor(m);if(x.tagName==="VIDEO")x.controls=true;box.append(x)}
async function load(){if(!db){render();return}const [p,m,c,l]=await Promise.all([db.from("posts").select("*, visitor_sessions(display_name)").is("deleted_at",null).order("created_at",{ascending:false}).limit(50),db.from("post_media").select("*"),db.from("comments").select("*, visitor_sessions(display_name)").is("deleted_at",null).order("created_at"),db.from("likes").select("post_id")]);if(p.error)throw p.error;posts=p.data||[];index(m.data||[],mediaByPost,"post_id");index(c.data||[],commentsByPost,"post_id");likesByPost.clear();(l.data||[]).forEach(x=>likesByPost.set(x.post_id,(likesByPost.get(x.post_id)||0)+1));render()}
function subscribe(){if(!db||channel)return;channel=db.channel("memory-wall-live");["posts","post_media","comments","likes"].forEach(table=>channel.on("postgres_changes",{event:"*",schema:"public",table},load));channel.subscribe()}
function validate(files){files.forEach(f=>{if(f.size>MAX_FILE_SIZE)throw Error(`${f.name} is larger than 50 MB.`);if(!/^(image|video|audio)\//.test(f.type))throw Error(`${f.name} is not a permitted media type.`)})}
function previews(){const box=$("#previews");box.replaceChildren();selectedFiles.forEach((f,i)=>{const wrap=document.createElement("div"),remove=document.createElement("button");wrap.className="preview-item";let p=document.createElement(f.type.startsWith("video/")?"video":f.type.startsWith("audio/")?"audio":"img");p.src=f.previewUrl;if(p.tagName!=="IMG")p.controls=true;remove.type="button";remove.className="remove-preview";remove.textContent="×";remove.onclick=()=>{URL.revokeObjectURL(f.previewUrl);selectedFiles.splice(i,1);previews()};wrap.append(p,remove);box.append(wrap)})}
async function dimensions(file){return new Promise(r=>{const im=new Image();im.onload=()=>{r({width:im.width,height:im.height});URL.revokeObjectURL(im.src)};im.onerror=()=>r({});im.src=URL.createObjectURL(file)})}async function upload(postId){const records=[];for(const f of selectedFiles){const path=`${postId}/${crypto.randomUUID()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`,type=f.type.split("/")[0];let rec={post_id:postId,storage_path:path,media_type:type,mime_type:f.type,file_size:f.size};const u=await db.storage.from("post-media").upload(path,f,{contentType:f.type});if(u.error)throw u.error;if(type==="image")Object.assign(rec,await dimensions(f));const r=await db.from("post_media").insert(rec).select().single();if(r.error)throw r.error;records.push(r.data)}return records}
async function publish(){const name=$("#displayName").value.trim(),content=memoryText(),button=$("#publishPost");try{button.disabled=true;button.textContent="Publishing…";await getSession(name);let post,records;if(db){const r=await db.from("posts").insert({session_id:session.id,content,post_type:selectedFiles.length?"media":"text"}).select("*, visitor_sessions(display_name)").single();if(r.error)throw r.error;post=r.data;records=await upload(post.id)}else{post={id:crypto.randomUUID(),content,created_at:new Date().toISOString(),visitor_sessions:{display_name:name}};records=selectedFiles.map(f=>({post_id:post.id,storage_path:f.previewUrl,previewUrl:f.previewUrl,media_type:f.type.split("/")[0]}))}posts.unshift(post);mediaByPost.set(post.id,records);$("#confirmDialog").close();$("#memoryDialog").close();$("#memoryForm").reset();selectedFiles=[];$("#previews").replaceChildren();render();setTimeout(()=>alert("Memory posted successfully! 🎂"),80)}catch(e){alert(`Could not publish memory: ${e.message}`)}finally{button.disabled=false;button.innerHTML='Publish Memory <span>✦</span>'}}
function intro(){let n=0;const tick=()=>{n=Math.min(100,n+Math.ceil(Math.random()*5));$("#percentage").textContent=n;$("#loaderFill").style.width=`${n}%`;if(n<100)setTimeout(tick,110)};tick();const end=()=>{if(introDone)return;introDone=true;$("#intro").classList.add("hide")};$("#intro").addEventListener("click",end,{once:true});setTimeout(end,5400)}
function bind(){document.addEventListener("pointerdown",()=>{if(sessionStorage.getItem("mw-music")!=="off")setMusic(true)},{once:true});$("#addMemory").onclick=()=>$("#memoryDialog").showModal();$("#closeMemoryDialog").onclick=()=>$("#memoryDialog").close();$("#viewAll").onclick=()=>$("#feed").scrollIntoView();$("#soundToggle").onclick=()=>setMusic(sessionStorage.getItem("mw-music")==="off");$("#mediaInput").onchange=e=>{try{const add=[...e.target.files];validate(add);add.forEach(f=>{f.previewUrl=URL.createObjectURL(f);selectedFiles.push(f)});e.target.value="";previews()}catch(err){alert(err.message);e.target.value=""}};$("#previewPost").onclick=()=>{if(!$("#memoryForm").reportValidity())return;const p=$("#postPreview");p.replaceChildren();const b=document.createElement("b");b.textContent=$("#displayName").value;p.append(b,document.createElement("br"));addLinks(p,$("#message").value);p.append(document.createElement("br"),document.createTextNode(selectedFiles.length?`${selectedFiles.length} media attachment(s)`:"Text memory"));$("#confirmDialog").showModal()};$("#cancelPreview").onclick=()=>$("#confirmDialog").close();$("#backToEdit").onclick=()=>$("#confirmDialog").close();$("#publishPost").onclick=publish;$("#loadMore").onclick=()=>{visible+=10;renderFeed()};$("#closeLightbox").onclick=()=>$("#lightbox").close();$("#lightbox .prev").onclick=()=>{galleryIndex=(galleryIndex-1+gallery.length)%gallery.length;showGallery()};$("#lightbox .next").onclick=()=>{galleryIndex=(galleryIndex+1)%gallery.length;showGallery()}}
function particles(){const c=$("#particles"),x=c.getContext("2d"),d=Array.from({length:45},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.6+.3,v:Math.random()*.18+.03}));(function draw(){c.width=innerWidth;c.height=innerHeight;x.clearRect(0,0,c.width,c.height);d.forEach(a=>{if((a.y-=a.v)<0)a.y=innerHeight;x.fillStyle="rgba(112,229,255,.35)";x.beginPath();x.arc(a.x,a.y,a.r,0,7);x.fill()});requestAnimationFrame(draw)})()}
if(db)$("#configBanner").hidden=true;audio().volume=.25;const musicEnabled=sessionStorage.getItem("mw-music")!=="off";setMusic(musicEnabled,false);if(musicEnabled)audio().play().catch(()=>{});bind();particles();intro();load().then(subscribe).catch(console.error);
